### ISSUE TITLE
Plan go rewrite

### ISSUE THREAD

**Issue by edd** [vegaprotocol/ethereum-event-forwarder#13]
The event forwarder is in `node` for historical reasons. To better match up the rest of the software run by validators, this should be rewritten in golang.

**Comment by gordsport** [comment]
Hey @ValentinTrinque,
Is this superseded by the eef work you are doing to bring it into the core?

**Comment by ValentinTrinque** [comment]
Yes @gordsport yihbare right. I didn't see this issue previously.

**Comment by gordsport** [comment]
Closing as a duplicate as now superseded by: https://github.com/vegaprotocol/vega/issues/4553
