### ISSUE TITLE
Auto-update dockerhub readme with readme changes

### ISSUE THREAD

**Issue by edd** [vegaprotocol/ethereum-event-forwarder#3]
https://hub.docker.com/r/vegaprotocol/ethereum-event-forwarder has the README contents, but it is manually synced. This could be done by a build step so it doesn’t get out of sync

# Tasks
- [ ] Add github action to publish README when pushing image

**Comment by ValentinTrinque** [comment]
This project is deprecated and no longer supported, because it is now part of the Vega core node.
